######################################################################
# Automatically generated by qmake (3.1) Fri May 29 13:36:41 2026
######################################################################

TEMPLATE = app
TARGET = Dashboard
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += GaugeWidget.h \
           MainWindow.h \
           build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/CMakeFiles/ShowIncludes/foo.h \
           build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/DashboardApp_autogen/include/ui_MainWindow.h \
           out/build/debug/CMakeFiles/ShowIncludes/foo.h \
           out/build/debug/DashboardApp_autogen/include/ui_MainWindow.h \
           /build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/DashboardApp_autogen/include/ui_MainWindow.h \
           /GaugeWidget.h \
           build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/DashboardApp_autogen/EWIEGA46WW/moc_GaugeWidget.cpp \
           build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/DashboardApp_autogen/EWIEGA46WW/moc_MainWindow.cpp \
           out/build/debug/DashboardApp_autogen/EWIEGA46WW/moc_GaugeWidget.cpp \
           out/build/debug/DashboardApp_autogen/EWIEGA46WW/moc_MainWindow.cpp
FORMS += mainwindow.ui
SOURCES += GaugeWidget.cpp \
           main.cpp \
           MainWindow.cpp \
           build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/DashboardApp_autogen/mocs_compilation.cpp \
           build/CMakeFiles/4.3.0-rc3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/CMakeFiles/ShowIncludes/main.c \
           out/build/debug/DashboardApp_autogen/mocs_compilation.cpp \
           build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/CMakeFiles/4.3.0-rc3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           out/build/debug/CMakeFiles/ShowIncludes/main.c \
           out/build/debug/CMakeFiles/3.31.6-msvc6/CompilerIdCXX/CMakeCXXCompilerId.cpp
TRANSLATIONS += build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/CMakeFiles/DashboardApp.dir/compiler_depend.ts \
                build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/CMakeFiles/DashboardApp_autogen.dir/compiler_depend.ts \
                build/Desktop_Qt_6_8_3_MSVC2022_64bit-Debug/CMakeFiles/DashboardApp_autogen_timestamp_deps.dir/compiler_depend.ts
